In [1]:
import numpy as np

In [2]:
## Creating an array of integers(-10 - 10)
a=np.array(range(-10,10))
a

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [3]:
## 2.creating an array of D
D=np.array(range(18))+3
D

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [4]:
## a.creating a varible x
x=D[1:10]
x

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
## b. creating a varible y
y=x[::-1]
y

array([12, 11, 10,  9,  8,  7,  6,  5,  4])

In [6]:
## c.creating a varible z
z=D[::-1]
z

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3])

# # 3.Numpy arrays are better than lists in python


# A numpy arrays is a grid of values,all of the same type, and is indexed by a tuple of non-negative integers. the no.of dimensions is the rank of the array, the shape of an array is a tuple of integers giving the size of the array along each dimension.

# A list is the python equivalent of array, but is resizeable and can contain elements in diffrent types.

# # 4.The data types supported by Numpy

# **BUILT-IN Data types
# i -integer
# b -boolean
# u -unsigned
# f -float
# c -complex float
# m -time delta
# M -date time
# O -object
# S -string
# U -unicode string
# V -void

# **Scalar Data types
# bool_ -return boolean true or false
# int_ -default integer type(int 64 or 34)
# intc -identical to integer in c(int 64 or 32)
# intp -integer value used for indexing
# int8 -assigning 8bit integer value(-128 to 127)
# int16 -assigning 16bit integer value(-32768 to 32767)
# int32 –assigning 32-bit integer value(-2147483648 to 2147483647)
# int32 –assigning 64-bit integer value(-9223372036854775808 to 9223372036854775807)
# uint8 –assigning unsigned 8-bit integer value(0 to 255)
# uint16 – It is for assigning unsigned 16-bit integer value (0 to 65535)
# uint32 – It is for assigning unsigned 32-bit integer value (0 to 4294967295)
# uint64 – It is for assigning unsigned 64-bit integer value (0 to 18446744073709551615)
# float_ –assign float values.
# float16 –half precision float values.
# float32 –single-precision float values.
# float64 –double-precision float values.
# complex_ –assign complex values.
# complex64 –represent two 32-bit float complex values (real and imaginary)
# complex128 –represent two 64-bit float complex values (real and imaginary)
